name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra

    - name: Convert all Markdown files to PDF
      run: |
        find . -name '*.md' -exec sh -c 'pandoc "$0" -o "${0%.md}.pdf"' {} \;
    - name: Commit PDFs
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add **/*.pdf
            git commit -m "Automated PDF generation" -a || echo "No changes to commit"
            git push
    - name: Upload all PDFs
      uses: actions/upload-artifact@v2
      with:
        name: PDFs
        path: '**/*.pdf'
