name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert all Markdown files to PDF
      run: |
        find . -name '*.md' -exec sh -c 'pandoc "$0" -o "${0%.md}.pdf"' {} \;

    - name: Upload all PDFs
      uses: actions/upload-artifact@v2
      with:
        name: Converted-PDFs
        path: |
          **/*.pdf
